name: format
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dev dependencies
        run: npm install --only=dev
      - name: Run Prettier
        run: npx prettier --check .
