name: lint
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        name: ESLint
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
            - name: Setup node
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: latest
            - name: Install dev dependencies
              run: npm install --only=dev
            - name: Run ESLint
              run: npx eslint .
